export const DAILY_PROMPTS = {
  ko: [
    "오늘 나를 미소짓게 한 작은 순간이 있었나요?",
    "오늘 감사했던 사람이 있다면 누구인가요?",
    "오늘 내 몸이 해준 것 중 감사한 게 있나요?",
    "오늘 먹은 것 중 맛있었던 것이 있었나요?",
    "오늘 배운 것이나 새롭게 알게 된 것이 있나요?",
    "오늘 나에게 친절하게 대해준 사람이 있었나요?",
    "오늘 밖의 날씨나 자연에서 감사한 게 있었나요?",
    "오늘 잘 해냈다고 느낀 순간이 있었나요?",
    "오늘 편안함을 느낀 장소나 상황이 있었나요?",
    "오늘 나를 웃게 만든 것이 있었나요?",
    "최근 연락이 닿아서 반가웠던 사람이 있나요?",
    "오늘 내가 사용한 물건 중 소중하게 느껴진 게 있나요?",
    "오늘 잠깐이라도 즐거웠던 순간은 언제였나요?",
    "오늘 나를 위해 한 일이 있었나요?",
    "오늘 집에서 감사하게 느껴진 것이 있었나요?",
    "오늘 어떤 도전을 했나요? 작은 것도 괜찮아요.",
    "오늘 떠오른 좋은 생각이나 아이디어가 있었나요?",
    "오늘 내가 가진 것 중 감사한 것이 있었나요?",
    "오늘 무언가를 완료했다는 뿌듯함이 있었나요?",
    "오늘 음악이나 소리 중 기분 좋게 만든 게 있었나요?",
    "오늘 누군가에게 도움을 받았나요?",
    "오늘 내가 누군가에게 도움이 된 순간이 있었나요?",
    "오늘 기억에 남을 것 같은 장면이 있었나요?",
    "오늘 충분히 쉴 수 있었나요?",
    "오늘 창밖이나 하늘을 바라본 순간이 있었나요?",
    "오늘 나 자신에게 칭찬해주고 싶은 것이 있나요?",
    "오늘 맡은 향기나 촉감 중 기분 좋은 게 있었나요?",
    "오늘 기대되는 일이 있었나요?",
    "오늘 시간을 함께 보낸 사람이 있었나요?",
    "오늘 하루를 한 마디로 표현한다면 무엇인가요?",
  ],
  en: [
    "Was there a small moment today that made you smile?",
    "Was there someone you felt grateful for today?",
    "Is there something your body did today that you're grateful for?",
    "Was there something you ate today that tasted wonderful?",
    "Did you learn or discover something new today?",
    "Was there someone who was kind to you today?",
    "Was there something about the weather or nature you're grateful for today?",
    "Was there a moment today where you felt you did well?",
    "Was there a place or situation where you felt at ease today?",
    "Was there something that made you laugh or smile today?",
    "Has there been someone you were happy to reconnect with recently?",
    "Was there something you used today that felt meaningful?",
    "When was even a brief moment of joy for you today?",
    "Did you do something kind for yourself today?",
    "Was there something at home you felt grateful for today?",
    "What challenge did you take on today? Small ones count too.",
    "Was there a good thought or idea that came to you today?",
    "Is there something you have that you felt grateful for today?",
    "Was there a sense of accomplishment in finishing something today?",
    "Was there music or a sound that lifted your mood today?",
    "Did someone help you out today?",
    "Was there a moment you helped someone else today?",
    "Is there a scene from today you'd like to remember?",
    "Were you able to rest and recharge today?",
    "Was there a moment you looked out a window or up at the sky today?",
    "Is there something you'd like to praise yourself for today?",
    "Was there a scent or sensation that felt pleasant today?",
    "Was there something you were looking forward to today?",
    "Did you spend quality time with someone today?",
    "If you could describe today in one word, what would it be?",
  ],
  ja: [
    "今日、小さなことで笑顔になった瞬間はありましたか？",
    "今日、感謝している人はいますか？",
    "今日、自分の体がしてくれたことで感謝できることはありますか？",
    "今日食べたもので、おいしかったものはありましたか？",
    "今日、学んだことや新しく知ったことはありますか？",
    "今日、親切にしてくれた人はいましたか？",
    "今日の天気や自然で感謝できることはありましたか？",
    "今日、うまくできたと感じた瞬間はありましたか？",
    "今日、安心できた場所や状況はありましたか？",
    "今日、笑わせてくれたものはありましたか？",
    "最近、再会できてうれしかった人はいますか？",
    "今日使ったもので、大切に感じたものはありますか？",
    "今日、少しでも楽しかった瞬間はいつですか？",
    "今日、自分のためにしたことはありますか？",
    "今日、家の中で感謝できることはありましたか？",
    "今日、どんな挑戦をしましたか？小さいことでも大丈夫です。",
    "今日、良い考えやアイデアが浮かびましたか？",
    "今日、自分が持っているもので感謝できることはありますか？",
    "今日、何かをやり遂げた達成感はありましたか？",
    "今日、気分を良くしてくれた音楽や音はありましたか？",
    "今日、誰かに助けてもらいましたか？",
    "今日、誰かの役に立てた瞬間はありましたか？",
    "今日、記憶に残したい場面はありましたか？",
    "今日、十分に休めましたか？",
    "今日、窓の外や空を見た瞬間はありましたか？",
    "今日、自分自身を褒めてあげたいことはありますか？",
    "今日、心地よい香りや感触はありましたか？",
    "今日、楽しみにしていることはありましたか？",
    "今日、一緒に時間を過ごした人はいましたか？",
    "今日一日を一言で表すとしたら何ですか？",
  ],
}

export function getTodayPrompt(locale = 'ko') {
  const prompts = DAILY_PROMPTS[locale] ?? DAILY_PROMPTS.ko
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000
  )
  return prompts[dayOfYear % prompts.length]
}
